In [1]:
import numpy as np

nk1 = 4
nk2 = 3
nk3 = 1

kx = np.linspace(0, 1, nk1)
ky = np.linspace(0, 1, nk2)
kz = np.linspace(0, 1, nk3)

In [69]:
nk1 = 4
nk2 = 3
nk3 = 1

In [70]:
kx = np.linspace(0, 1, nk1)
ky = np.linspace(0, 1, nk2)
kz = np.linspace(0, 1, nk3)

In [4]:
klist = np.zeros((nk1 * nk2 * nk3, 3))
klist

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
weightlist = np.ones((nk1 * nk2 * nk3, 1)) / (nk1 * nk2 * nk3)
weightlist

array([[0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333],
       [0.08333333]])

In [72]:
klist = np.empty([0,3])
for k1 in kx:
    k1val = np.array([k1, 0, 0]) if nk1 > 1 else np.array([0, 0, 0])
    for k2 in ky:
        k2val = np.array([0, k2, 0]) if nk2 > 1 else np.array([0, 0, 0])
        for k3 in kz:
            k3val = np.array([0, 0, k3]) if nk3 > 1 else np.array([0, 0, 0])
            kval = k1val + k2val + k3val
            print(kval)
            klist = np.vstack((klist, kval))


[0. 0. 0.]
[0.  0.5 0. ]
[0. 1. 0.]
[0.33333333 0.         0.        ]
[0.33333333 0.5        0.        ]
[0.33333333 1.         0.        ]
[0.66666667 0.         0.        ]
[0.66666667 0.5        0.        ]
[0.66666667 1.         0.        ]
[1. 0. 0.]
[1.  0.5 0. ]
[1. 1. 0.]


In [78]:
def gen_kpts(nk1, nk2, nk3):
    kx = np.linspace(0, 1, nk1)
    ky = np.linspace(0, 1, nk2)
    kz = np.linspace(0, 1, nk3)
    klist = np.empty([0,3])
    for k1 in kx:
        k1val = np.array([k1, 0, 0]) if nk1 > 1 else np.array([0, 0, 0])
        for k2 in ky:
            k2val = np.array([0, k2, 0]) if nk2 > 1 else np.array([0, 0, 0])
            for k3 in kz:
                k3val = np.array([0, 0, k3]) if nk3 > 1 else np.array([0, 0, 0])
                kval = k1val + k2val + k3val
                print(kval)
                klist = np.vstack((klist, kval))
    return klist

gen_kpts(nk1, nk2, nk3)

[0. 0. 0.]
[0.  0.5 0. ]
[0. 1. 0.]
[0.33333333 0.         0.        ]
[0.33333333 0.5        0.        ]
[0.33333333 1.         0.        ]
[0.66666667 0.         0.        ]
[0.66666667 0.5        0.        ]
[0.66666667 1.         0.        ]
[1. 0. 0.]
[1.  0.5 0. ]
[1. 1. 0.]


array([[0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.33333333, 0.        , 0.        ],
       [0.33333333, 0.5       , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [0.66666667, 0.        , 0.        ],
       [0.66666667, 0.5       , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.5       , 0.        ],
       [1.        , 1.        , 0.        ]])

In [80]:
def gen_kpts(nk1, nk2, nk3):
    kx = np.linspace(0, 1, nk1)
    ky = np.linspace(0, 1, nk2)
    kz = np.linspace(0, 1, nk3)
    weightlist = np.ones((nk1 * nk2 * nk3, 1)) / (nk1 * nk2 * nk3)
    klist = np.empty([0,3])

    for k1 in kx:
        k1val = np.array([k1, 0, 0]) if nk1 > 1 else np.array([0, 0, 0])
        for k2 in ky:
            k2val = np.array([0, k2, 0]) if nk2 > 1 else np.array([0, 0, 0])
            for k3 in kz:
                k3val = np.array([0, 0, k3]) if nk3 > 1 else np.array([0, 0, 0])
                kval = k1val + k2val + k3val
                print(kval)
                klist = np.vstack((klist, kval))
    
    list = np.hstack((klist, weightlist))

    return list

In [81]:
gen_kpts(4, 3, 1)

[0. 0. 0.]
[0.  0.5 0. ]
[0. 1. 0.]
[0.33333333 0.         0.        ]
[0.33333333 0.5        0.        ]
[0.33333333 1.         0.        ]
[0.66666667 0.         0.        ]
[0.66666667 0.5        0.        ]
[0.66666667 1.         0.        ]
[1. 0. 0.]
[1.  0.5 0. ]
[1. 1. 0.]


array([[0.        , 0.        , 0.        , 0.08333333],
       [0.        , 0.5       , 0.        , 0.08333333],
       [0.        , 1.        , 0.        , 0.08333333],
       [0.33333333, 0.        , 0.        , 0.08333333],
       [0.33333333, 0.5       , 0.        , 0.08333333],
       [0.33333333, 1.        , 0.        , 0.08333333],
       [0.66666667, 0.        , 0.        , 0.08333333],
       [0.66666667, 0.5       , 0.        , 0.08333333],
       [0.66666667, 1.        , 0.        , 0.08333333],
       [1.        , 0.        , 0.        , 0.08333333],
       [1.        , 0.5       , 0.        , 0.08333333],
       [1.        , 1.        , 0.        , 0.08333333]])

In [77]:
list

array([[0.        , 0.        , 0.        , 0.08333333],
       [0.        , 0.5       , 0.        , 0.08333333],
       [0.        , 1.        , 0.        , 0.08333333],
       [0.33333333, 0.        , 0.        , 0.08333333],
       [0.33333333, 0.5       , 0.        , 0.08333333],
       [0.33333333, 1.        , 0.        , 0.08333333],
       [0.66666667, 0.        , 0.        , 0.08333333],
       [0.66666667, 0.5       , 0.        , 0.08333333],
       [0.66666667, 1.        , 0.        , 0.08333333],
       [1.        , 0.        , 0.        , 0.08333333],
       [1.        , 0.5       , 0.        , 0.08333333],
       [1.        , 1.        , 0.        , 0.08333333]])

In [82]:
np.savetxt("kptBZ.csv", list, fmt="%10.6f", delimiter=",")

In [83]:
1/15

0.06666666666666667

In [84]:
1/25

0.04